// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: helloworld.proto
// </auto-generated>
#pragma warning disable 1591
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using grpc = global::Grpc.Core;

namespace Helloworld.Proto {
  public static partial class Hello
  {
    static readonly string __ServiceName = "helloworld.Hello";

    static readonly grpc::Marshaller<global::Helloworld.Proto.GreetRequest> __Marshaller_GreetRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Helloworld.Proto.GreetRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Helloworld.Proto.GreetResponse> __Marshaller_GreetResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Helloworld.Proto.GreetResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::Helloworld.Proto.GreetRequest, global::Helloworld.Proto.GreetResponse> __Method_Greeting = new grpc::Method<global::Helloworld.Proto.GreetRequest, global::Helloworld.Proto.GreetResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Greeting",
        __Marshaller_GreetRequest,
        __Marshaller_GreetResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Helloworld.Proto.HelloworldReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Hello</summary>
    public abstract partial class HelloBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Helloworld.Proto.GreetResponse> Greeting(global::Helloworld.Proto.GreetRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Hello</summary>
    public partial class HelloClient : grpc::ClientBase<HelloClient>
    {
      /// <summary>Creates a new client for Hello</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public HelloClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Hello that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public HelloClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected HelloClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected HelloClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Helloworld.Proto.GreetResponse Greeting(global::Helloworld.Proto.GreetRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return Greeting(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Helloworld.Proto.GreetResponse Greeting(global::Helloworld.Proto.GreetRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Greeting, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Helloworld.Proto.GreetResponse> GreetingAsync(global::Helloworld.Proto.GreetRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GreetingAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Helloworld.Proto.GreetResponse> GreetingAsync(global::Helloworld.Proto.GreetRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Greeting, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override HelloClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new HelloClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(HelloBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Greeting, serviceImpl.Greeting).Build();
    }

  }
  public static partial class World
  {
    static readonly string __ServiceName = "helloworld.World";

    static readonly grpc::Marshaller<global::Helloworld.Proto.GreetRequest> __Marshaller_GreetRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Helloworld.Proto.GreetRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Helloworld.Proto.GreetResponse> __Marshaller_GreetResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Helloworld.Proto.GreetResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::Helloworld.Proto.GreetRequest, global::Helloworld.Proto.GreetResponse> __Method_Greeting = new grpc::Method<global::Helloworld.Proto.GreetRequest, global::Helloworld.Proto.GreetResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Greeting",
        __Marshaller_GreetRequest,
        __Marshaller_GreetResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Helloworld.Proto.HelloworldReflection.Descriptor.Services[1]; }
    }

    /// <summary>Base class for server-side implementations of World</summary>
    public abstract partial class WorldBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Helloworld.Proto.GreetResponse> Greeting(global::Helloworld.Proto.GreetRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for World</summary>
    public partial class WorldClient : grpc::ClientBase<WorldClient>
    {
      /// <summary>Creates a new client for World</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public WorldClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for World that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public WorldClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected WorldClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected WorldClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Helloworld.Proto.GreetResponse Greeting(global::Helloworld.Proto.GreetRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return Greeting(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Helloworld.Proto.GreetResponse Greeting(global::Helloworld.Proto.GreetRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Greeting, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Helloworld.Proto.GreetResponse> GreetingAsync(global::Helloworld.Proto.GreetRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GreetingAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Helloworld.Proto.GreetResponse> GreetingAsync(global::Helloworld.Proto.GreetRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Greeting, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override WorldClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new WorldClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(WorldBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Greeting, serviceImpl.Greeting).Build();
    }

  }
}
#endregion
